politist_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'politist_app'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='politist_app/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('analytics/', views.AnalyticsView, name='analytics'),
    path('tweetlist/', views.TweetListView, name='tweet_list'),
    path('tweetlist/', views.TweetListView, name='tweet_list')
]

politist_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from politist_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('politist/', include('politist_app.urls')),
    path('politist/', include('django.contrib.auth.urls')),
    path('dashboard/', views.DashboardView, name='dashboard'),
    path('logout_success/', views.LogoutSuccessView.as_view(), name='logout_success'),
    path('login_success/', views.LoginSuccessView.as_view(), name='login_success'),
]

politist_app/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib import auth


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

class Search(models.Model):
    topic_search = models.CharField(max_length = 100, verbose_name='Topic Search')

    def __str__(self):
        return self.topic_search

        #model

politist_app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from . models import Search


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()
    #overriding the default field labels
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Name'
        self.fields['email'].label = 'Email'

class SearchForm(forms.ModelForm):

    class Meta:
        model = Search
        fields = ('topic_search',)
        widgets = {
            'topic_search': forms.TextInput(attrs = {'class': 'form-control form-control-lg',
                                                        'placeholder': 'Type something...'}),
        }

politist_app/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from . import forms
from politist_app.models import Search
from politist_app.forms import SearchForm
from django.views.generic import (View, TemplateView, DetailView, CreateView)
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from politist_app.utils import get_tweets, sentiment_analyser, toi, get_related_tweets
import requests
import json


tweet_list = []
tweet_data = []
s = ''

class LogoutSuccessView(TemplateView):
    template_name = 'politist_app/app_templates/logout_success.html'

class IndexView(TemplateView):
    template_name = 'politist_app/app_templates/index.html'

class SignupView(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'politist_app/registration/signup.html'


@login_required
def DashboardView(request):
    global tweet_list
    global tweet_data
    toi_list = toi()
    form = SearchForm()
    toi_list = toi()
    if request.method == "POST":
        form = SearchForm(request.POST)
        
        if form.is_valid():
            global s
            s = form.save(commit=True)
            
            tweet_list = get_tweets(str(s))
            tweet_data = get_related_tweets(str(s))
            return render(request, 'politist_app/app_templates/tweet_list.html', {'tweet_list': tweet_list, 's': s, 'tweet_data': tweet_data})
        else:
            print("Invalid Form!")

    return render(request, 'politist_app/app_templates/dashboard.html', {'form': form, 'toi_list': toi_list})
    
@login_required
def AnalyticsView(request):
    global tweet_list
    global tweet_data
    global s
    emotion, score, emotion_dict, reaction = sentiment_analyser(tweet_list)
    return render(request, 'politist_app/app_templates/analytics.html', {'score': score, 'emotion': emotion,"emotion_dict": emotion_dict, 'reaction': reaction, 's': s})

politist_app/templates/politist_app/app_templates/analytics.html
{% extends 'politist_app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}
            <br>

            <div class="card mx-auto border-primary mb-3" style="width: 70rem;">
                    <div class="card-header">
                            <h1 class="my-auto" id="x3">Outcome</h1>
                    </div>
                    <div class="card-body">
                   
                      
                      <p class="card-text">
                          <ul>
                              <li>
                                    <h4>
                                            The display of <b>{{ emotion }}</b> Emotion is highest with a probability of <b>{{ score }} %</b> 
                                        </h4>
                              </li>
                              <li>
                                    <h4>
                                            This shows that public will show <b>{{ reaction }}</b> reaction to the trending topic of '{{ s }}'
                                        </h4>
                              </li>
                          </ul>
                            
                                
                      </p>
                      
                    </div>
                  </div>
                  <br>
            <!-- <div id="piechart"></div> -->
    <!-- <div id="mouseoverdiv"></div> -->
    <div class="row">
            <div class="col-xl-8 col-lg-7">
              <!-- Area Chart -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
                </div>
                <div class="card-body">
                  <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                  </div>
                  <hr />
                </div>
              </div>
      
              <!-- Bar Chart -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
                </div>
                <div class="card-body">
                  <div class="chart-bar">
                    <canvas id="myBarChart"></canvas>
                  </div>
                  <hr />
                </div>
              </div>
            </div>
      
            <!-- Donut Chart -->
            <div class="col-xl-4 col-lg-5">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <div class="chart-pie pt-4">
                    <canvas id="myPieChart"></canvas>
                  </div>
                  <hr />
                </div>
              </div>
            </div>
          </div>

    <script>
        var anger_score = {{ emotion_dict.anger.score }};
        var anger_count = {{ emotion_dict.anger.count }};

        var analytical_score = {{ emotion_dict.analytical.score }};
        var analytical_count = {{ emotion_dict.analytical.count }};

        var tentative_score = {{ emotion_dict.tentative.score }};
        var tentative_count = {{ emotion_dict.tentative.count }};

        var confident_score = {{ emotion_dict.confident.score }};
        var confident_count = {{ emotion_dict.confident.count }};

        var fear_score = {{ emotion_dict.fear.score }};
        var fear_count = {{ emotion_dict.fear.count }};

        var sadness_score = {{ emotion_dict.sadness.score }};
        var sadness_count = {{ emotion_dict.sadness.count }};

        var joy_score = {{ emotion_dict.joy.score }};
        var joy_count = {{ emotion_dict.joy.count }};

       

// Set new default font family and font color to mimic Bootstrap's default styling
(Chart.defaults.global.defaultFontFamily = "Nunito"),
  '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
Chart.defaults.global.defaultFontColor = "#858796";

// Pie Chart Example
var ctx = document.getElementById("myPieChart");
var myPieChart = new Chart(ctx, {
  type: "doughnut",
  data: {
    labels: ["Sadness", "Joy", "Tentative", "Confident", "Anger", "Analytical", "Fear"],
    datasets: [
      {
        data: [sadness_score, joy_score, tentative_score, confident_score, anger_score, analytical_score, fear_score],
        backgroundColor: ["#4e73df", "#1cc88a", "#36b9cc", "#cddc39", "#69f0ae", "#ef6c00", "#dd2c00"],
        hoverBackgroundColor: ["#2e59d9", "#17a673", "#2c9faf", "#dd2c00", "#4e73df", "#36b9cc", "#69f0ae"],
        hoverBorderColor: "rgba(234, 236, 244, 1)"
      }
    ]
  },
  options: {
    maintainAspectRatio: false,
    tooltips: {
      backgroundColor: "rgb(255,255,255)",
      bodyFontColor: "#858796",
      borderColor: "#dddfeb",
      borderWidth: 1,
      xPadding: 15,
      yPadding: 15,
      displayColors: false,
      caretPadding: 10
    },
    legend: {
      display: false
    },
    cutoutPercentage: 80
  }
});

// Set new default font family and font color to mimic Bootstrap's default styling
(Chart.defaults.global.defaultFontFamily = "Nunito"),
  '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
Chart.defaults.global.defaultFontColor = "#858796";

function number_format(number, decimals, dec_point, thousands_sep) {
  // *     example: number_format(1234.56, 2, ',', ' ');
  // *     return: '1 234,56'
  number = (number + "").replace(",", "").replace(" ", "");
  var n = !isFinite(+number) ? 0 : +number,
    prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
    sep = typeof thousands_sep === "undefined" ? "," : thousands_sep,
    dec = typeof dec_point === "undefined" ? "." : dec_point,
    s = "",
    toFixedFix = function(n, prec) {
      var k = Math.pow(10, prec);
      return "" + Math.round(n * k) / k;
    };
  // Fix for IE parseFloat(0.55).toFixed(0) = 0;
  s = (prec ? toFixedFix(n, prec) : "" + Math.round(n)).split(".");
  if (s[0].length > 3) {
    s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
  }
  if ((s[1] || "").length < prec) {
    s[1] = s[1] || "";
    s[1] += new Array(prec - s[1].length + 1).join("0");
  }
  return s.join(dec);
}

// Area Chart Example
var ctx = document.getElementById("myAreaChart");
var myLineChart = new Chart(ctx, {
  type: "line",
  data: {
    labels: ["Sadness", "Joy", "Tentative", "Confident", "Anger", "Analytical", "Fear"],
    datasets: [
      {
        label: "Score ",
        lineTension: 0.3,
        backgroundColor: "rgba(78, 115, 223, 0.05)",
        borderColor: "rgba(78, 115, 223, 1)",
        pointRadius: 3,
        pointBackgroundColor: "rgba(78, 115, 223, 1)",
        pointBorderColor: "rgba(78, 115, 223, 1)",
        pointHoverRadius: 3,
        pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
        pointHoverBorderColor: "rgba(78, 115, 223, 1)",
        pointHitRadius: 10,
        pointBorderWidth: 2,
        data: [sadness_score, joy_score, tentative_score, confident_score, anger_score, analytical_score, fear_score]
      }
    ]
  },
  options: {
    maintainAspectRatio: false,
    layout: {
      padding: {
        left: 10,
        right: 25,
        top: 25,
        bottom: 0
      }
    },
    scales: {
      xAxes: [
        {
          time: {
            unit: "date"
          },
          gridLines: {
            display: false,
            drawBorder: false
          },
          ticks: {
            maxTicksLimit: 7
          }
        }
      ],
      yAxes: [
        {
          ticks: {
            maxTicksLimit: 5,
            padding: 10,
            // Include a dollar sign in the ticks
            callback: function(value, index, values) {
              return " " + number_format(value);
            }
          },
          gridLines: {
            color: "rgb(234, 236, 244)",
            zeroLineColor: "rgb(234, 236, 244)",
            drawBorder: false,
            borderDash: [2],
            zeroLineBorderDash: [2]
          }
        }
      ]
    },
    legend: {
      display: false
    },
    tooltips: {
      backgroundColor: "rgb(255,255,255)",
      bodyFontColor: "#858796",
      titleMarginBottom: 10,
      titleFontColor: "#6e707e",
      titleFontSize: 14,
      borderColor: "#dddfeb",
      borderWidth: 1,
      xPadding: 15,
      yPadding: 15,
      displayColors: false,
      intersect: false,
      mode: "index",
      caretPadding: 10,
      callbacks: {
        label: function(tooltipItem, chart) {
          var datasetLabel =
            chart.datasets[tooltipItem.datasetIndex].label || "";
          return datasetLabel + number_format(tooltipItem.yLabel);
        }
      }
    }
  }
});

// Set new default font family and font color to mimic Bootstrap's default styling
(Chart.defaults.global.defaultFontFamily = "Nunito"),
  '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
Chart.defaults.global.defaultFontColor = "#858796";

function number_format(number, decimals, dec_point, thousands_sep) {
  // *     example: number_format(1234.56, 2, ',', ' ');
  // *     return: '1 234,56'
  number = (number + "").replace(",", "").replace(" ", "");
  var n = !isFinite(+number) ? 0 : +number,
    prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
    sep = typeof thousands_sep === "undefined" ? "," : thousands_sep,
    dec = typeof dec_point === "undefined" ? "." : dec_point,
    s = "",
    toFixedFix = function(n, prec) {
      var k = Math.pow(10, prec);
      return "" + Math.round(n * k) / k;
    };
  // Fix for IE parseFloat(0.55).toFixed(0) = 0;
  s = (prec ? toFixedFix(n, prec) : "" + Math.round(n)).split(".");
  if (s[0].length > 3) {
    s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
  }
  if ((s[1] || "").length < prec) {
    s[1] = s[1] || "";
    s[1] += new Array(prec - s[1].length + 1).join("0");
  }
  return s.join(dec);
}

// Bar Chart Example
var ctx = document.getElementById("myBarChart");
var myBarChart = new Chart(ctx, {
  type: "bar",
  data: {
    labels: ["Sadness", "Joy", "Tentative", "Confident", "Anger", "Analytical", "Fear"],
    datasets: [
      {
        label: "Count ",
        backgroundColor: "#4e73df",
        hoverBackgroundColor: "#2e59d9",
        borderColor: "#4e73df",
        data: [sadness_count, joy_count, tentative_count, confident_count, anger_count, analytical_count, fear_count]
      }
    ]
  },
  options: {
    maintainAspectRatio: false,
    layout: {
      padding: {
        left: 10,
        right: 25,
        top: 25,
        bottom: 0
      }
    },
    scales: {
      xAxes: [
        {
          time: {
            unit: "emotions"
          },
          gridLines: {
            display: false,
            drawBorder: false
          },
          ticks: {
            maxTicksLimit: 6
          },
          maxBarThickness: 25
        }
      ],
      yAxes: [
        {
          ticks: {
            min: 0,
            max: 8,
            maxTicksLimit: 5,
            padding: 10,
            // Include a dollar sign in the ticks
            callback: function(value, index, values) {
              return number_format(value);
            }
          },
          gridLines: {
            color: "rgb(234, 236, 244)",
            zeroLineColor: "rgb(234, 236, 244)",
            drawBorder: false,
            borderDash: [2],
            zeroLineBorderDash: [2]
          }
        }
      ]
    },
    legend: {
      display: false
    },
    tooltips: {
      titleMarginBottom: 10,
      titleFontColor: "#6e707e",
      titleFontSize: 14,
      backgroundColor: "rgb(255,255,255)",
      bodyFontColor: "#858796",
      borderColor: "#dddfeb",
      borderWidth: 1,
      xPadding: 15,
      yPadding: 15,
      displayColors: false,
      caretPadding: 10,
      callbacks: {
        label: function(tooltipItem, chart) {
          var datasetLabel =
            chart.datasets[tooltipItem.datasetIndex].label || "";
          return datasetLabel + number_format(tooltipItem.yLabel);
        }
      }
    }
  }
});

    </script>

    {% endblock %}

politist_app/templates/politist_app/app_templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <script src="{% static 'js/master.js' %}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <title>Politist</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand mybrand" href="{% url 'index' %}"><i class="fas fa-parking lo"></i><b class="me"> Politist</b></a>

    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'dashboard' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-search"></i> Search</button></a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'politist_app:logout' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-sign-out-alt"></i> Sign Out</button></a></li>
          <li class="nav-item user_text v"><a class="nav-link">Hello, {{ user.username }}</a></li>

        {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'politist_app:login' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-sign-in-alt"></i> Sign In</button></a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'politist_app:signup' %}"><button type="button" class="btn btn-outline-light"><i class="fas fa-user-plus"></i> Register</button></a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
    {% block content %}

    {% endblock %}

    
  </div>

</body>
</html>

politist_app/templates/politist_app/app_templates/dashboard.html
{% extends 'politist_app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}
      <br>
      <div class="container">
        <div class="card mx-auto border-primary mb-3 x4">
          <div class="card-header text-center">
            <h1 class="my-auto" id="x4">Search Trending Topics</h1>
          </div>
          <div class="card-body x4">
            <form method="POST">
              {% csrf_token %}
              <div class="input-group mb-3">
              {{ form }}
              <div class="input-group-append">
              <button class="btn btn-success" type="submit">Search</button>
              </div>
              </div>
              </form>
            </div>
          </div>
        </div>
      <br>
        
      <div class="container-fluid">
          <br />
          <div class="card-deck">
            <div class="card border-primary mb-3">
              <img class="card-img-top" src="{{toi_list.articles.0.urlToImage}}" alt="Card image cap" />
              <div class="card-body">
                <a href="{{toi_list.articles.0.url}}"><h5 class="card-title">{{toi_list.articles.0.title}}</h5></a>
                <p class="card-text">
                  <small class="text-muted">Last updated 3 mins ago</small>
                </p>
              </div>
            </div>
            <div class="card border-primary mb-3">
              <img class="card-img-top" src="{{toi_list.articles.1.urlToImage}}" alt="Card image cap" />
              <div class="card-body">
                <a href="{{toi_list.articles.1.url}}"><h5 class="card-title">{{toi_list.articles.1.title}}</h5></a>
                  <small class="text-muted">Last updated 3 mins ago</small>
                </p>
              </div>
            </div>
            <div class="card border-primary mb-3">
              <img class="card-img-top" src="{{toi_list.articles.2.urlToImage}}" alt="Card image cap" />
              <div class="card-body">
                <a href="{{toi_list.articles.2.url}}"><h5 class="card-title">{{toi_list.articles.2.title}}</h5></a>
                  <small class="text-muted">Last updated 3 mins ago</small>
                </p>
              </div>
            </div>
            <div class="card border-primary mb-3">
              <img class="card-img-top" src="{{toi_list.articles.3.urlToImage}}" alt="Card image cap" />
              <div class="card-body">
                <a href="{{toi_list.articles.3.url}}"><h5 class="card-title">{{toi_list.articles.3.title}}</h5></a>
                <p class="card-text">
                  <small class="text-muted">Last updated 3 mins ago</small>
                </p>
              </div>
            </div>
          </div>
    
          <br />
    
          <div class="card-deck">
            <div class="card border-primary mb-3">
              <img class="card-img-top" src="{{toi_list.articles.4.urlToImage}}" alt="Card image cap" />
              <div class="card-body">
                <a href="{{toi_list.articles.4.url}}"><h5 class="card-title">{{toi_list.articles.4.title}}</h5></a>
                <p class="card-text">
                  <small class="text-muted">Last updated 3 mins ago</small>
                </p>
              </div>
            </div>
            <div class="card border-primary mb-3">
              <img class="card-img-top" src="{{toi_list.articles.6.urlToImage}}" alt="oops" />
              <div class="card-body">
                <a href="{{toi_list.articles.6.url}}"><h5 class="card-title">{{toi_list.articles.6.title}}</h5></a>
                <p class="card-text">
                  <small class="text-muted">Last updated 3 mins ago</small>
                </p>
              </div>
            </div>
    
    
          </div>
          <br />
        </div>
    








      <!-- <div class="container">
        {% for item in toi_list.articles %}
          <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{ item.urlToImage }}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><a href="{{ item.url }}">{{ item.title }}</a></h5>
            </div>
          </div>
          <br>
          {% endfor %}
      </div> -->
    {% endblock %}

politist_app/templates/politist_app/app_templates/index.html
{% extends 'politist_app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}

        <div class="container">
            <br>
            <br>
            <br>
            <br>
            
            <div class="card mx-auto border-primary mb-3" style="width: 60rem;">
                    <div class="card-header display-3 text-center">What is Politist about?</div>
                        <div class="card-body">
                        
                          <h3 class="display-5">This is a Web App which predicts the amount of influence social media has on the outcome of Politics.</h3>
                          <hr>
                            <h2 class="display-4">Influence Today, Change Tomorrow!!</h2>
                        </div>  
                      </div>
        </div>

    {% endblock %}

politist_app/templates/politist_app/app_templates/login_success.html
{% extends 'politist_app/app_templates/base.html' %}
{% load bootstrap4 %}

    {% block content %}

        <div class="container">
            <h1>hello logged in</h1>
            <form class="sample" method="POST">
              {% csrf_token %}
              <h4>{{git_username_form}} <input type="submit" class="button" value="Search"></h4>
            </form>
        </div>

    {% endblock %}

politist_app/templates/politist_app/app_templates/logout_success.html
{% extends 'politist_app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}
        <br>
        <div class="container">
            <div class="card mx-auto">
              <div class="card-header text-center">
                <h1 class="my-auto" id="x5">Logged Out</h1>
              </div>
              <div class="card-body text-center">
                <p class="x5 my-auto display-5">You have been succesfully logged out! <i class="far fa-smile"></i></p>
                <p class="x5 my-auto"><a href="{% url 'politist_app:login' %}">Visit again</a></p>
              </div>
            </div>
          </div>

    {% endblock %}

politist_app/templates/politist_app/app_templates/tweet_list.html
{% extends 'politist_app/app_templates/base.html' %}
{% load bootstrap4 %}
    
    {% block content %}
    <br>
        <div class="container">
            <ul style="list-style-type:none;">
                {% for item in tweet_data.statuses %}
                    <li>
                        <div class="card mx-auto border-primary mb-3" style="width: 60rem;">
                            
                            <h5 class="card-title mx-auto x6">@{{ item.user.screen_name }}</h5>
                            <hr>
                            <div class="card-body">
                                 <h5 class="card-title">{{ item.full_text }}</h5>
                            </div>
                        </div>
                    </li>
                    <br>
                    
                {% endfor %}
            </ul>
        </div>
        <div class="container">
            <a class="nav-link" href="{% url 'politist_app:analytics' %}"><button type="button" class="btn btn-primary btn-block">Analyze <i class="fab fa-twitter tw"></i></button></a>
        </div>

    {% endblock %}